stages:
  - build
  - test
  - publish

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  DOCKER_TLS_CERTDIR: "/certs"

cache:
  paths:
    - .m2/repository

build_job:
  stage: build
  image: eclipse-temurin:21-jdk-jammy
  script:
    - chmod +x mvnw
    - ./mvnw clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

test_job:
  stage: test
  image: eclipse-temurin:21-jdk-jammy
  script:
    - chmod +x mvnw
    - ./mvnw test

publish_job:
  stage: publish
  image: docker:24.0.7
  services:
    - docker:24.0.7-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest