spring.application.name=employee-service

spring.datasource.url=jdbc:h2:mem:employee_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.liquibase.changelog=classpath:db/changelog/db.changelog-master.xml